
DFTtype = "Wannier90" #  OpenMX Wannier90
Wannier90type = "OpenMX" # OpenMX  VASP  EcalJ
#scf_fname = "../examples/NiO/4cell/Ni6.0_O5.0-s2p2d2f1-4.25_0.0-4.180-k10/nio.scfout"
#scf_fname = "../examples/NiO/4cell/0_0/nio.scfout"
#result_file = "../examples/NiO/4cell/Ni6.0_O5.0-s2p2d2f1-4.25_0.0-4.180-k10/nio.HWR"
result_file = "nio.HWR"
atom12 = [[1,1],[1,2]]

[orbitals]
orbitalselection = "on" # on, off
orbital_mask1 = [4,5]
orbital_mask2 = [4,5]
orbital_mask_option = "unmask" # #mask #unmask
orbital_mask_name = "eg_eg"
[wannier_optional]
# atom position info dose not exists at OpenMX wannier
atomnum = 4
atompos = [[0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
        [0.250, 0.250, 0.250],
        [0.750, 0.750, 0.750]]
atoms_orbitals_list = [[1,3,5,7,9],[2,4,6,8,10],[11,13,15],[12,14,16]]

#@enum DFTtype OpenMX = 1 Wannier90 = 2 NULLDFT = -1
#@enum Wannier90type OpenMXWF = 1 VASPWF = 2 EcalJWF = 3  NULLWANNIER = -1
