# This is a TOML document. Boom.
DFTtype = "OpenMX" #  OpenMX Wannier90
#Wannier90type = "OpenMX" # OpenMX  VASP  EcalJ
#result_file = "../examples/NiO/4cell/Ni6.0_O5.0-s2p2d2f1-4.25_0.0-4.180-k10/nio.scfout"
result_file = "nio.scfout"
atom12 = [[1,1],[1,2]]

[orbitals]
orbitalselection = "off"
