title: Jx
description: J-eXchange, MFT (Magnetic force theory) based spin exchange calculation from Full OpenMX DFT/Wannier Hamiltonian.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
email: hongkeeyoon@kaist.ac.kr

sass:
  sass_dir: ./_sass
